steps:
 - trigger: "book-dot-feelpp-dot-org"
   label: ":package: Generate :book:"
   async: true
 - name: ':$TARGET ${CXX}'
   command: .buildkite/steps/build.sh
   agents:
     docker: true
     ubuntu: "16.04"
   env:
     PROJECT: angiotk
     CXX: clang++-4.0
     BUILD_JOBS: 10
     FROM: feelpp/feelpp-toolboxes
     TARGET: ubuntu:16.04
     FEELPP_BRANCH: develop
     CMAKE_FLAGS: -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-inconsistent-missing-override" -DBUILD_MODULE_Meshing=ON -DBUILD_MODULE_Filtering=ON -DBUILD_MODULE_Segmentation=ON -DBUILD_MODULE_ParticleTracer=ON -DBUILD_EXAMPLES=ON
 - wait
 - name: ':rocket: :whale: deploy :$TARGET'
   command: .buildkite/steps/release.sh
   agents:
     docker: true
     ubuntu: "16.04"
   branches: develop master
   env:
     PROJECT: angiotk
     TARGET: ubuntu:16.04
