= How {angioTK} works

== Introduction
The AngioTK project's aim is to allow computer simulation (fluid dynamics, particle tracing) in 3D models of blood vessels reconstructed automatically from medical images (MRI files).

Therefore, AngioTK is structured as a pipeline whose initial input - the MRI files - are carried and transformed throughout multiple processes ordered as follows:

`+[MRI FILE] -> 1.Filtering -> 2.Mesh Generation -> 3.Computer Fluid Dynamics -> 4.Particle Tracing+`


Each of these processes corresponds to a dedicated software module:

== Filtering Module (ITK/Medipy/RORPO/VMTK)

Images are filtered to prepare them for mesh extraction and made isotropic if necessary.

The main goal here is to highlight tubular structures so they can be extracted in the next step.
See the xref:module-filtering.adoc[Image Filtering Module] for more information.


== Meshing Module (VTK/VMTK/GMSH)

A 3D mesh is generated by extracting the tubular structure of blood vessels from the images. 
Some final filtering is then applied to correct and smooth the resulting geometry.

Further information and a detailed description of the different steps involved are available in the xref:module-meshing.adoc[Meshing Module].

== Fluid Flow Module (Feel++)

Runs computer fluid dynamics code to simulate blood flow in the veins and arteries and possibly the interaction between the blood and the vessels.

Further information is available in the xref:module-flow.adoc[Fluid Flow Module].

== Particle Tracer Module (Paraview)
Useful to visualize particle trajectories inside the blood vessels.
