
message("")
message(STATUS "[AngioTK] Enabled modules: (Enable with -DBUILD_MODULE_*)")
file( GLOB modules ${AngioTk_SOURCE_DIR}/Modules/* ) 
foreach( module ${modules} )
  if( IS_DIRECTORY ${module} )
    get_filename_component( moduleName ${module} NAME)
    if( ${BUILD_MODULE_${moduleName}} )
        message("- ${moduleName}: ON")
    else()
        message("- ${moduleName}: OFF")
    endif()
  endif()
endforeach()

message("")
message(STATUS "[AngioTK] Build commands:")
message("- make         : Builds the enabled AngioTK modules (libraries and executables)") 
message("- make install : Builds the enabled AngioTK modules, then install them with pipeline examples to ${CMAKE_INSTALL_PREFIX}") 
message("")
